config/routes.rb
Rails.application.routes.draw do
  resources :notes
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home/index'
  resources :homeworks
  resources :class_groups
  resources :presentations
  resources :presentation_items
  resources :students

  resources :homeworks do
    resources :comments
  end

  root "home#index"

  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # root to: "homeworks#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :student
  belongs_to :homework

  has_many :presentations, dependent: :destroy
  has_many :presentation_items, through: :presentations
  has_one :note, dependent: :destroy, inverse_of: :comment
  validates :result, numericality: { only_integer: true }
  accepts_nested_attributes_for :note, reject_if: proc { |attributes| attributes['text'].blank? }


  def addclass
    if resubmit
      css_class = 'resubmit'
    elsif merit
      css_class = "merit"
    else
      css_class = ''
    end
    css_class
  end

  def calculate_class (total_score)
    if result == -1
      css_class = "amber"
    elsif result.to_f/total_score.to_f > 0.85
      css_class = "merit"
    elsif result.to_f/total_score.to_f < 0.49
      self.resubmit = true
      css_class = "resubmit"
    else
      css_class = ''
    end
    self.save
    css_class
  end

  def set_flag(flag)
    if flag
      student = Student.find(self.student_id)
      student.flag = true
      student.save
    end
  end

# Horrible, horrible hack that fortunately no longer needed.

#  def delete_empty_notes
#    if self.note.text.length == 0
#      self.note.destroy
#    end
#  end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :get_homework

  # GET /comments
  # GET /comments.json
  def index
  @comments =   Comment.joins(:student).merge(Student.order(last_name: :asc).where("is_current = ?", true)).where("homework_id = ? ", @homework.id)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ExportPdf.new(@homework, PresentationItem.all)
        send_data pdf.render,
          filename: @homework.class_group.name + "_Homework_" + @homework.date.strftime("%d_%b_%y") + ".pdf",
          type: 'application/pdf',
          disposition: 'inline'
      end
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    respond_to do |format|
      format.html
      format.json {render :show}
      format.js {render :show}
    end
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @students = @homework.class_group.students.where("is_current = ?", true).sort_by{ |m| m.last_name.downcase }
    @comment.presentations.build
  end

  # GET /comments/1/edit
  def edit
    @comment.build_note if @comment.note.nil?

  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.set_flag(params[:flag])
    @comment.homework_id = @homework.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to homework_comments_url, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js { redirect_to homework_comments_url(), notice: 'Comment was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
#        @comment.delete_empty_notes
        @comment.set_flag(params[:flag])
        format.html { redirect_to homework_comments_url(), notice: 'Comment was successfully updated.' }
        format.js {render :index}
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to homework_comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def get_homework
      @homework = Homework.find(params[:homework_id])
      @students = @homework.class_group.students.where("is_current = ?", true).sort_by{ |m| m.last_name.downcase }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(
        :student_id,
        :date,
        :title,
        :grade,
        :result,
        :www,
        :area_for_development,
        :dirt,
        :spelling,
        :homework_id,
        :resubmit,
        :merit,
        :not_submitted,
        note_attributes: [:text],
        presentation_item_ids: []

        )
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: @comment, url: (@comment.new_record? ? [@homework, @comment]: [@homework, @comment]), remote: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h2 class="head"> <%= @comment.student.full_name %> </h2>

<!--
  <div class="field">
    <%= form.label :student_id %>
    <%= form.collection_select(:student_id, @students, :id, :full_name, prompt: true ) %>
  </div>
-->

<div class="wrapper" >
  <div class="col" style="width:363px">
    <div class="field">
      <%= form.label :result, "Score" %>
      <%= form.number_field :result, size: 3%>
    </div>
    <div class="field " style="clear:both;">
        <%= form.check_box :not_submitted %>
        <%= form.label :not_submitted %>

    </div>
  </div>
  <div class="col">
    <%= form.fields_for :note do |note_form| %>
      Notes<br />
      <%= note_form.text_area :text, cols: 57, rows: 8 %>
    <% end %>
  </div>

</div>

<div class="wrapper">

  <div class="col">
    <%= form.label :www, "General comments" %>
    <%= form.text_area :www, cols: 57, rows: 8%>
  </div>

  <div class="col">
    <%= form.label :area_for_development, "Homework comments"%>
    <%= form.text_area :area_for_development, cols: 57, rows: 8 %>
  </div>

  <div class="col">
    <%= form.label :dirt, "DIRT" %>
    <%= form.text_area :dirt, cols: 10, rows: 8, :value =>"Correct your mistakes"%>
  </div>

  <div class="col">
    <%= form.label :spelling %>
    <%= form.text_area :spelling, cols: 10, rows: 8 %>
  </div>

  <div class="col" style="width:200px">
    <%= form.fields_for :presentations do |pres_form| %>
      <%= form.collection_check_boxes(:presentation_item_ids, PresentationItem.all, :id, :full_item) do |cb| %>
        <%= cb.check_box %>
        <%= cb.label %>
        <br />
      <% end %>
    <% end %>
  </div>

</div>


<div class="wrapper; width:270px">
  <div class="col" style="width:90px;">
    <%= form.check_box :resubmit %>
    <%= form.label :resubmit %>
  </div>

  <div class="col" style="width:70px">
    <%= form.check_box :merit %>
    <%= form.label :merit %>
  </div>

  <div class="col">
    <%= check_box_tag 'flag'  %>
    <%= label_tag :flag %>

  </div>
</div>

<br />


<%= form.submit 'Submit', :id => 'form_submit' %> &nbsp; &nbsp;
<%= link_to "cancel", "#", id: "cancel"%>





<% end %>

app/views/comments/_row.html.erb
<tr class="<%= comment.calculate_class(comment.homework.score) %>" id="n_<%= comment.id %>">
  <td><% if comment.student.flag %>
    <%= image_tag("flags-icon-png-10292.png", size: "16", id: "cx_#{comment.student.id}") %>
      <% end %>
  </td>
  <td><%= link_to comment.student.full_name, edit_homework_comment_url(@homework, comment), :id => "edit_#{comment.id}" , remote: true%></td>
  <td><%= comment.result %>
    <% if comment.merit %>
      <%= image_tag("flags-icon-png-10291.png", size: "16") %>
    <% end %>
    <% if comment.not_submitted %>
      <%= image_tag("warning-16", size: "16") %>
    <% end %>
    <% if comment.resubmit %>
      <%= image_tag("flags-icon-png-10292.png", size: "16") %>
    <% end %>
  </td>
  <td><%= comment.www %></td>
  <td><%= comment.area_for_development %></td>
  <td><%= comment.dirt %></td>
  <td><%= comment.spelling %></td>
  <td><%= link_to 'Show', student_path(comment.student) %></td>
  <td><%= link_to 'Destroy', homework_comment_url(@homework, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/comments/edit.html.erb
<h1><%= @comment.student.full_name%></h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', homework_comment_url(@homework, @comment) %> |
<%= link_to 'Back', homework_comments_path %>

app/views/comments/edit.js.erb
$('#holder').html("<%= j (render 'form') %>");
$('#holder').slideDown(350);
//$('#task-form').html("<%= j (render 'form') %>");
//$('#task-form').slideDown(350);

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feedback for <%= @homework.title %></h1>
<h2> Form: <%= @homework.class_group.name %> | Date:  <%= @homework.date.strftime("%d %b %y") %> </h2>
<p>Number students: <%= @homework.class_group.students.size  =%></p>
<p>Maximum score: <%= @homework.score  =%></p>
<% bad_uns = @homework.get_attribute("not_submitted") %>
<p>Not submitted: <%= bad_uns.count %></p>
<% bad_uns.each do |b_u| %>
  <ul>
  <li><%= b_u.student.full_name %></li>
  </ul>
<% end %>


<div id="task-form" style="display:none; border: 1px black solid; padding: 5px;"></div>
<div id = "dialog"  title = "Dialog Title goes here...">
  <span id="text"></span>
</div>
<table>
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>Student</th>
      <th>Score</th>
      <th>www</th>
      <th>Area for development</th>
      <th>Dirt</th>
      <th>Spelling</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <%= render 'row', comment: comment %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_homework_comment_path, :id => "new_comment", remote: true %> |
<%= link_to "Printable Form (PDF)", homework_comments_path(@homework, format: 'pdf') %>

<div id="form_holder">
</div>

app/views/comments/index.js.erb
$('tr#n_<%= @comment.id %>').replaceWith("<%= j (render 'row', comment: @comment) %>");
$('#holder').slideUp(350);
$("#h").remove();

$('tr#n_<%= @comment.id %>').effect( "highlight", "slow")

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', homework_comments_path %>

app/views/comments/new.js.erb
$('#new_comment').hide().after('<%= j render("form") %>');

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @comment.student.full_name %>
</p>



<p>
  <strong>Grade:</strong>
  <%= @comment.grade %>
</p>

<p>
  <strong>www:</strong>
  <%= @comment.www %>
</p>

<p>
  <strong>Area for development:</strong>
  <%= @comment.area_for_development %>
</p>

<p>
  <strong>Dirt:</strong>
  <%= @comment.dirt %>
</p>

<p>
  <strong>Spelling:</strong>
  <%= @comment.spelling %>
</p>

<h2> Presentation</h2>
<% @comment.presentations.each do |p| %>
  <p><%= p.presentation_item.heading %>  <%= p.presentation_item.category %> </p>

<% end %>


<%= link_to 'Edit', edit_homework_comment_url(@homework, @comment) %> |
<%= link_to 'Back', homework_comments_path %>