config/routes.rb
Rails.application.routes.draw do
  resources :notes
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home/index'
  resources :homeworks
  resources :class_groups
  resources :presentations
  resources :presentation_items
  resources :students

  resources :homeworks do
    resources :comments
  end

  root "home#index"

  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # root to: "homeworks#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :class_group_id, presence: true

  belongs_to :class_group
  has_many :comments, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.order('class_group_id ASC', :last_name)
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @homeworks = @student.class_group.homeworks
    @comments = Comment.where("student_id=?", @student.id).order('created_at ASC')
    respond_to do |format|
      format.html
      format.pdf do
        pdf = StudentReportPdf.new(@comments, PresentationItem.all)
        send_data pdf.render,
          filename: "export.pdf",
          type: 'application/pdf',
          disposition: 'inline'
      end
    end

  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:last_name, :first_name, :class_group_id, :is_current, :flag, :is_pp, :is_sen)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :is_pp,  "PP" %>
    <%= form.check_box :is_pp %>
  </div>

  <div class="field">
    <%= form.label :is_sen, "SEN" %>
    <%= form.check_box :is_sen %>
  </div>

  <div class="field">
    <%= form.label :class_group_id %>
    <%= form.collection_select(:class_group_id, ClassGroup.order(:year, :name).where('is_archive!= TRUE'), :id, :name, prompt: true ) %>
  </div>

  <div class="field">
    <%= form.label :is_current %>
    <%= form.check_box :is_current %>
  </div>

  <div class="field">
    <%= form.label :flag %>
    <%= form.check_box :flag %>
  </div>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>
<%= link_to 'New Student', new_student_path %>
<p><button>Show/hide archive</button></p>

<table>
  <thead>
    <tr>
      <th> &nbsp; </th>
      <th> &nbsp; </th>
      <th>First name</th>
      <th>Last name</th>
      <th> &nbsp; </th>
      <th>Class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr<% unless student.is_current %> class="not_current" <% end %>>
        <td class="c<%= student.class_group.name %>">&nbsp</td>
        <td><% if student.flag %>
              <%= image_tag("flags-icon-png-10292.png", size: "16", title: 'Flagged' , alt: "flagged") %>
            <% end %>
        </td>
        <td><%= link_to student.first_name, student %></td>
        <td><%= link_to student.last_name, student %></td>
        <td><% if student.is_pp %>
              <%= image_tag("blue_flag.png", size: "16",  title: 'PP', alt: "PP") %>
            <% end %>
            <% if student.is_sen %>
              <%= image_tag("orange_flag.png", size: "16", title: 'SEN', alt: "SEN") %>
            <% end %>
        </td>
        <td><%= student.class_group.name %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>
<p><button>Show/hide archive</button></p>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= @student.full_name %> </h1>


<p>
  <strong>Class:</strong>
  <%= @student.class_group.name %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

<h2>Notes</h2>
<p><button>Show/hide archive</button></p>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Homework</th>
      <th>Note</th>
    </tr>
  </thead>
  <tbody>
    <tbody>
      <% @comments.each do |comment| %>
          <% unless comment.note.nil? %>
            <tr class = "<% if comment.note.is_archive ==true %> not_current<% end %>" >
                <td> <%= comment.note.created_at.strftime("%d %b %y") %> </td>
                <td> <%= comment.homework.title %></td>
                <td> <%= comment.note.text %> </td>
            </tr>
          <% end %>
      <% end %>
    </tbody>
  </table>



<h2>Homeworks</h2>
<p><button>Show/hide archive</button></p>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Comments</th>
      <th>Feedback</th>
      <th>DIRT</th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
    <tr class="<%= comment.addclass %><% if comment.homework.is_archive ==TRUE %> not_current<% end %>">
        <td> <%= comment.homework.date.strftime("%d %b %y") %> </td>
        <td> <%= comment.homework.title %> </td>
        <td> <%= comment.www %> </td>
        <td> <%= comment.area_for_development %> </td>
        <td> <%= comment.dirt %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<p><button>Show/hide archive</button></p>

<%= link_to "Printable Form (PDF)", student_path(format: 'pdf') %>