config/routes.rb
Rails.application.routes.draw do
  resources :notes
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home/index'
  resources :homeworks
  resources :class_groups
  resources :presentations
  resources :presentation_items
  resources :students

  resources :homeworks do
    resources :comments
  end

  root "home#index"

  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # root to: "homeworks#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/class_group.rb
class ClassGroup < ApplicationRecord

  has_many :students, dependent: :destroy
  has_many :homeworks, dependent: :destroy


  def get_scores(homework)

    comments = Comment.where("homework_id = ? ", homework.id)
    scores = Hash.new
    comments.each do |comment|
      attributes = {:result => comment.result, :is_merit => comment.merit, :resubmit => comment.resubmit, :not_submitted => comment.not_submitted, :id => comment.id}
      scores.store(comment.student_id, attributes)
    end
    scores
  end


  def count_students
      count = Student.where("class_group_id = ? AND is_current = ?", self.id, true).count
  end


  def number_flags
    count = Student.where("class_group_id = ? AND flag = ?", self.id, true).count
  end

  def set_colour(homework, result)
    total_score = homework.score
    if result == -1
      css_class = 'amber'
    elsif result.to_f/total_score.to_f > 0.85
      css_class = "merit"
    elsif result.to_f/total_score.to_f < 0.49
      css_class = "resubmit"
    else
      css_class = 'amber'
    end
    css_class
  end

end

app/controllers/class_groups_controller.rb
class ClassGroupsController < ApplicationController
  before_action :set_class_group, only: [:show, :edit, :update, :destroy]

  # GET /class_groups
  # GET /class_groups.json
  def index
    @class_groups = ClassGroup.order(:year, :name)

  end

  # GET /class_groups/1
  # GET /class_groups/1.json
  def show
    @students = Student.where("class_group_id = ? AND is_current = ?", @class_group.id, true).order(:last_name)
    @homeworks = Homework.where("class_group_id = ? AND is_archive = ?", @class_group.id, false ).order(:date)
  end

  # GET /class_groups/new
  def new
    @class_group = ClassGroup.new
  end

  # GET /class_groups/1/edit
  def edit
  end

  # POST /class_groups
  # POST /class_groups.json
  def create
    @class_group = ClassGroup.new(class_group_params)

    respond_to do |format|
      if @class_group.save
        format.html { redirect_to @class_group, notice: 'Class group was successfully created.' }
        format.json { render :show, status: :created, location: @class_group }
      else
        format.html { render :new }
        format.json { render json: @class_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_groups/1
  # PATCH/PUT /class_groups/1.json
  def update
    respond_to do |format|
      if @class_group.update(class_group_params)
        format.html { redirect_to @class_group, notice: 'Class group was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_group }
      else
        format.html { render :edit }
        format.json { render json: @class_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_groups/1
  # DELETE /class_groups/1.json
  def destroy
    @class_group.destroy
    respond_to do |format|
      format.html { redirect_to class_groups_url, notice: 'Class group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_group
      @class_group = ClassGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_group_params
      params.require(:class_group).permit(:name, :year, :is_archive, :academic_year)
    end
end

app/helpers/class_groups_helper.rb
module ClassGroupsHelper
end

app/views/class_groups/_form.html.erb
<%= form_with(model: class_group, local: true) do |form| %>
  <% if class_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class_group.errors.count, "error") %> prohibited this class_group from being saved:</h2>

      <ul>
      <% class_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :academic_year %>
    <%= form.text_area :academic_year %>
  </div>



  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>




  <div class="field">
    <%= form.label :is_archive %>
    <%= form.check_box :is_archive %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/class_groups/edit.html.erb
<h1>Editing Class Group</h1>

<%= render 'form', class_group: @class_group %>

<%= link_to 'Show', @class_group %> |
<%= link_to 'Back', class_groups_path %>

app/views/class_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Class Groups</h1>

<table>
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>Name</th>
      <th>Year</th>
      <th>Number <br />in class</th>
      <th>Academic <br />year</th>
      <th>Number <br />flagged</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_groups.each do |class_group| %>
    <tr style="border-bottom: 1px solid;" <% if class_group.is_archive %> class="not_current" <% end %> > 
        <td class="c<%= class_group.name %>">&nbsp</td>
        <td><%= link_to class_group.name, class_group %></td>
        <td><%= class_group.year %></td>
        <td><%= class_group.count_students %></td>
        <td><%= class_group.academic_year %></td>
        <td style="color:red"><%= class_group.number_flags %></td>
        <td><%= link_to 'Edit', edit_class_group_path(class_group) %></td>
        <td><%= link_to 'Destroy', class_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class Group', new_class_group_path %>
<p><button>Show/hide archive</button></p>

app/views/class_groups/new.html.erb
<h1>New Class Group</h1>

<%= render 'form', class_group: @class_group %>

<%= link_to 'Back', class_groups_path %>

app/views/class_groups/show.html.erb
<div id="class_group_page<%if @class_group.is_archive%>_archive<% end%>">

<p id="notice"><%= notice %></p>


  <h1><%= @class_group.name %></h1>


<p>
  <strong>Academic year:</strong>
  <%= @class_group.academic_year %>
</p>

<p>
  <strong>Year:</strong>
  <%= @class_group.year %>
</p>

<p>
  <strong>Status:</strong>
  <% if @class_group.is_archive == true  %>
    <span style ="color:red">ARCHIVED</span>
  <% else %>
    <span style ="color:green">CURRENT</span>
  <% end %>
</p>


<p>
  <strong>Number in class:</strong>
  <%= @students.count %>
</p>

<%= link_to 'Edit', edit_class_group_path(@class_group) %> |
<%= link_to 'Back', class_groups_path %>



<!-- HTML -->
<div id = "dialog"  title = "Dialog Title goes here...">
  <p><span style="font-weight: bold;">General comments: </span><span id="www"></span></p>
  <p><span style="font-weight: bold;">Homework comments: </span><span id="afd"></span></p>
</div>



<h3>Students</h3>
<table>
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>First name</th>
      <th>Last name</th>
      <th>&nbsp;</th>
      <% @homeworks.each do |homework| %>
        <th><p><%= link_to homework.title[0..4], homework_comments_path(homework)%><br /><%= homework.score %></th>
        <% end %>
    </tr>
  </thead>
  <tbody>

  <% @students.each do |student| %>
    <tr>
      <td id="f_<%= student.id %>">
        <% if student.flag %>
          <%= image_tag("flags-icon-png-10292.png", size: "16", title: 'Flagged' , alt: "flagged", id: 'i_' + student.id.to_s, class: "show") %>
        <% else %>
          <%= image_tag("flags-icon-png-10292.png", size: "16", title: 'Flagged' , alt: "flagged", id: 'i_' + student.id.to_s, class: "hidden") %>
        <% end %>
      </td>
      <td><%= link_to student.first_name, student_url(student) %></td>
      <td><%= link_to student.last_name, student_url(student) %></td>
      <td><% if student.is_pp %>
            <%= image_tag("blue_flag.png", size: "16",  title: 'PP', alt: "PP") %>
          <% end %>
          <% if student.is_sen %>
            <%= image_tag("orange_flag.png", size: "16", title: 'SEN', alt: "SEN") %>
          <% end %>
      </td>
      <% @homeworks.each do |homework| %>
        <% results = @class_group.get_scores(homework) %>

        <% # if results[student.id][:result].present? %>
        <% if results[student.id].present? %>

          <% result = results[student.id][:result] %>
          <% id = results[student.id][:id] %>
            <td class="centre <%= @class_group.set_colour(homework, result) %>" >
              <% if result == -1 %>
                  &mdash;
                <% else %>
                  <span id="s_<%= id %>_<%= homework.id %>"> <%= result %></span>
              <% end %>
              <% if results[student.id][:is_merit] %>
                <%= image_tag("flags-icon-png-10291.png", size: "12") %>
              <% end %>
              <% if results[student.id][:resubmit] %>
                <%= image_tag("flags-icon-png-10292.png", size: "12") %>
              <% end %>
              <% if results[student.id][:not_submitted] %>
                <%= image_tag("warning-16", size: "12") %>
              <% end %>
        <% else %>
          <td class="centre"> &mdash; </td>
        <% end %>
      <% end %>
    </tr>
  <% end %>

  </tbody>
</table>
</div>