config/routes.rb
Rails.application.routes.draw do
  resources :notes
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home/index'
  resources :homeworks
  resources :class_groups
  resources :presentations
  resources :presentation_items
  resources :students

  resources :homeworks do
    resources :comments
  end

  root "home#index"

  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # root to: "homeworks#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/homework.rb
class Homework < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :class_group

  validates :title, presence: true
  validates :date, presence: true
  validates :score, numericality: { only_integer: true }

  def build_comments
    students = self.class_group.students
    students.sort_by(&:last_name).each do |student|
      comment = Comment.new({:homework_id => self.id, :student_id => student.id, :result => "-1"})
      comment.save
    end

  end

  def get_attribute(attribute)
      Comment.where("homework_id = ? AND #{attribute} = ?", self.id, true).includes(:student).order("students.last_name")
  end

  def pretty_boolean(bool)
    bool ? "&#10003;" : "&#10005;"
  end


end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]


  # GET /homeworks
  # GET /homeworks.json
  def index
  #  @homeworks = Homework.order('created_at ASC')
    @homeworks = Homework.order(:class_group_id, 'created_at ASC')
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
    @students = @homework.class_group.students.sort
    @comments = Comment.where("homework_id=?",@homework.id).includes(:student).order("students.last_name")
    respond_to do |format|
      format.html
      format.pdf do
        pdf = HomeworkReportPdf.new(@homework, @comments, @students)
        send_data pdf.render,
          filename: @homework.class_group.name + "_Homework_Report_" + @homework.date.strftime("%d_%b_%y") + ".pdf",
          type: 'application/pdf',
          disposition: 'inline'
      end
    end



  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = Homework.new(homework_params)

    respond_to do |format|
      if @homework.save
        @homework.build_comments
        format.html { redirect_to homework_comments_url(@homework), notice: 'Homework was successfully created.' }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_params
      params.require(:homework).permit(:class_group_id, :date, :title, :is_worksheet, :score, :is_archive)
    end
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/homeworks/_form.html.erb
<%= form_with(model: homework, local: true) do |form| %>
  <% if homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
      <% homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :class_group_id %>
    <%= form.collection_select(:class_group_id, ClassGroup.order(:year, :name).where('is_archive!= TRUE'), :id, :name, prompt: true ) %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :is_worksheet %>
    <%= form.check_box :is_worksheet %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homeworks/edit.html.erb
<h1>Editing Homework</h1>

<%= render 'form', homework: @homework %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homeworks</h1>

<p><%= link_to 'New Homework', new_homework_path %></p>

<table>
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>Class group</th>
      <th>Date</th>
      <th>Title</th>
      <th>W/S</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
    <% unless homework.class_group.is_archive == true %>
      <tr>
        <td class="c<%= homework.class_group.name %>">&nbsp</td>
        <td  ><%= link_to homework.class_group.name, class_group_path(homework.class_group) %></td>
        <td><%= homework.date.strftime("%d %b %y")%></td>
        <td><%= link_to homework.title, homework_comments_path(homework) %></td>
        <td><%= raw homework.pretty_boolean(homework.is_worksheet) %></td>
        <td><%= link_to 'Report', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

app/views/homeworks/new.html.erb
<h1>New Homework</h1>

<%= render 'form', homework: @homework %>

<%= link_to 'Back', homeworks_path %>

app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="head">
  <h2>Report: <%= @homework.class_group.name %> <%= @homework.title %> </h2>
  <h3><%= @homework.date.strftime("%d %b %y")%></h3>
</div>

<div class="wrapper">

  <div class = "col" style="border:1px solid black;">
    <% merits = @homework.get_attribute("merit") %>
    <h3>Merits: <%= merits.count %></h3>
    <% merits.each do |m| %>
      <ul>
      <li><%= m.student.full_name %></li>
      </ul>
    <% end %>
  </div>
  <div class = "col" style=" border:1px solid black; ">
    <% resubmit = @homework.get_attribute("resubmit") %>
    <h3>Resubmits: <%= resubmit.count %></h3>
    <% resubmit.each do |r| %>
      <ul>
      <li><%= r.student.full_name %></li>
      </ul>
    <% end %>
  </div>
  <div class = "col" style="border:1px solid black; ">
    <% not_submitted = @homework.get_attribute("not_submitted") %>
    <h3>Not submitted: <%= not_submitted.count %></h3>
    <% not_submitted.each do |n| %>
      <ul>
      <li><%= n.student.full_name %></li>
      </ul>
    <% end %>
  </div>

</div>


<div style="position:relative">

<p>&nbsp;</p>
<table>
  <thead>
    <tr>
      <th style="width:12%">Name</th>
      <th>Score</th>
      <th style="width:42%">WWW</th>
      <th style="width:40%">Notes</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.student.full_name %></td>
            <td class="centre ">
              <% if comment.result == -1 %>
                  &mdash;
                <% else %>
                  <%= comment.result %>
              <% end %>
              <% if comment.merit %>
                <%= image_tag("flags-icon-png-10291.png", size: "12") %>
              <% end %>
              <% if comment.resubmit %>
                <%= image_tag("flags-icon-png-10292.png", size: "12") %>
              <% end %>
              <% if comment.not_submitted %>
                <%= image_tag("warning-16", size: "12") %>
              <% end %>


        <td><%= comment.area_for_development %></td>
        <td> <% unless comment.note.nil? %>
              <%= comment.note.text %>
            <% end %>
        </td>

      </tr>
      <% end %>
  </tbody>
</table>
</div>





<%= link_to 'Back', homeworks_path %> |
<%= link_to "Printable Form (PDF)", homework_path(@homework, format: 'pdf') %>